#!/usr/bin/env bash
set -euo pipefail

# Static compatibility only: this checks the exact Create Fly members and invocation sites used by our Mixins.
# A passing result does not replace an in-game smoke test.
MINECRAFT_SERIES="${1:-26.2}"
REPORT_PATH="${2:-build/compatibility/create-fly-${MINECRAFT_SERIES}.md}"
METADATA_URL="https://api.modrinth.com/maven/maven/modrinth/create-fly/maven-metadata.xml"
ARTIFACT_URL="https://api.modrinth.com/maven/maven/modrinth/create-fly/%s/create-fly-%s.jar"

command -v curl >/dev/null
command -v javap >/dev/null
command -v unzip >/dev/null
command -v python3 >/dev/null

temp_dir="$(mktemp -d)"
trap 'rm -rf "$temp_dir"' EXIT
mkdir -p "$(dirname "$REPORT_PATH")"

mapfile -t versions < <(
    curl -fsSL "$METADATA_URL" | python3 -c '
import sys
import xml.etree.ElementTree as ET
root = ET.parse(sys.stdin).getroot()
for version in root.findall("./versioning/versions/version"):
    print(version.text)
'
)

printf '# Create Fly static compatibility report\n\n' > "$REPORT_PATH"
printf 'Minecraft series: `%s`  \n' "$MINECRAFT_SERIES" >> "$REPORT_PATH"
printf 'Generated by `scripts/check-create-fly-compatibility.sh`. A passing result is **static compatibility**, not an in-game guarantee.\n\n' >> "$REPORT_PATH"
printf '| Maven version | Create Fly mod version | Result | Missing or changed hook |\n| --- | --- | --- | --- |\n' >> "$REPORT_PATH"

found=0
for version in "${versions[@]}"; do
    [[ "$version" == "$MINECRAFT_SERIES"-* ]] || continue
    found=1

    jar_path="$temp_dir/create-fly.jar"
    details=()
    result='static-compatible'

    if ! curl -fsSL "$(printf "$ARTIFACT_URL" "$version" "$version")" -o "$jar_path"; then
        printf '| `%s` | n/a | download-failed | Could not download artifact |\n' "$version" >> "$REPORT_PATH"
        continue
    fi

    mod_version="$(unzip -p "$jar_path" fabric.mod.json | python3 -c 'import json, sys; print(json.load(sys.stdin).get("version", "unknown"))' 2>/dev/null || printf unknown)"
    display_source_api="$(javap -classpath "$jar_path" -p -s com.zurrtum.create.api.behaviour.display.DisplaySource 2>/dev/null || true)"
    display_source_code="$(javap -classpath "$jar_path" -p -c com.zurrtum.create.api.behaviour.display.DisplaySource 2>/dev/null || true)"
    context_api="$(javap -classpath "$jar_path" -p -s com.zurrtum.create.content.redstone.displayLink.DisplayLinkContext 2>/dev/null || true)"
    block_entity_api="$(javap -classpath "$jar_path" -p -s com.zurrtum.create.content.redstone.displayLink.DisplayLinkBlockEntity 2>/dev/null || true)"
    screen_api="$(javap -classpath "$jar_path" -p -s com.zurrtum.create.client.content.redstone.displayLink.DisplayLinkScreen 2>/dev/null || true)"
    screen_code="$(javap -classpath "$jar_path" -p -c com.zurrtum.create.client.content.redstone.displayLink.DisplayLinkScreen 2>/dev/null || true)"

    check() {
        local haystack="$1"
        local needle="$2"
        local label="$3"
        if [[ "$haystack" != *"$needle"* ]]; then
            details+=("$label")
        fi
    }

    check "$display_source_api" 'transferData(' 'DisplaySource.transferData'
    check "$display_source_api" 'provideText(' 'DisplaySource.provideText'
    check "$display_source_api" 'provideFlapDisplayText(' 'DisplaySource.provideFlapDisplayText'
    check "$display_source_code" 'provideText:' 'transferData -> provideText call'
    check "$display_source_code" 'provideFlapDisplayText:' 'transferData -> provideFlapDisplayText call'
    check "$context_api" 'sourceConfig()' 'DisplayLinkContext.sourceConfig'
    check "$block_entity_api" 'getSourceConfig()' 'DisplayLinkBlockEntity.getSourceConfig'
    check "$screen_api" 'void init()' 'DisplayLinkScreen.init'
    check "$screen_api" 'void onClose()' 'DisplayLinkScreen.onClose'
    check "$screen_api" 'DisplayLinkBlockEntity blockEntity' 'DisplayLinkScreen.blockEntity'
    check "$screen_code" 'DisplayLinkConfigurationPacket' 'onClose -> DisplayLinkConfigurationPacket call'

    if ((${#details[@]})); then
        result='incompatible'
    fi
    detail_text="${details[*]:-all static hooks found}"
    printf '| `%s` | `%s` | %s | %s |\n' "$version" "$mod_version" "$result" "$detail_text" >> "$REPORT_PATH"
done

if (( ! found )); then
    printf '| n/a | n/a | no-candidates | No Maven versions begin with `%s-` |\n' "$MINECRAFT_SERIES" >> "$REPORT_PATH"
fi

cat "$REPORT_PATH"
